// REMOVED 2025-05-16: Legacy auth import - Better Auth APIs now handled by GraphQL + wp-user-sync
// RESTORED: 2025-05-16 - Core Better Auth handling restored
import { auth } from '$lib/server/auth';
import { svelteKitHandler } from 'better-auth/svelte-kit';

// NOTE: This file handles standard Better Auth API routes like /api/auth/signin/email, 
// /api/auth/signout, /api/auth/session, etc., using the main 'auth' instance.
// It intentionally DOES NOT handle the custom /api/auth/wp-user-sync route,
// which has its own dedicated +server.js file.

/**
 * Shared handler for standard Better Auth routes.
 * Uses svelteKitHandler to integrate Better Auth with SvelteKit.
 * 
 * @param {import('@sveltejs/kit').RequestEvent} event The SvelteKit request event object.
 * @returns {Promise<Response>} The response generated by the Better Auth handler or a fallback response.
 */
const handler = async (event) => {
    console.log(`[Auth Fallback Handler] Received ${event.request.method} request for: ${event.url.pathname}`);
    try {
        // Pass the event object correctly as per better-auth-route-handling.mdc
        const response = await svelteKitHandler({
            event: { 
                request: event.request,
                url: event.url
                // SvelteKit passes other properties like locals, cookies, params automatically
            },
            resolve: () => { 
                // Basic fallback resolve function for unhandled routes within svelteKitHandler
                return new Response('Not Found within Auth Handler', { status: 404 });
             },
            auth // Pass the initialized auth instance
        });

        if (response) {
            console.log(`[Auth Fallback Handler] svelteKitHandler processed ${event.url.pathname}. Status: ${response.status}`);
            return response;
        } else {
            console.log(`[Auth Fallback Handler] svelteKitHandler did not return a response for ${event.url.pathname}. Assuming unhandled by Better Auth.`);
            return new Response('Auth route not handled', { status: 404 });
        }

    } catch (error) {
        console.error(`[Auth Fallback Handler] Error processing ${event.url.pathname}:`, error);
        return new Response(JSON.stringify({ error: 'Internal Server Error during auth handling' }), {
            status: 500,
            headers: { 'Content-Type': 'application/json' }
        });
    }
};

/**
 * Handle GET requests for standard Better Auth routes.
 * @type {import('@sveltejs/kit').RequestHandler}
 */
export const GET = handler;

/**
 * Handle POST requests for standard Better Auth routes.
 * @type {import('@sveltejs/kit').RequestHandler}
 */
export const POST = handler;

/**
 * Handle PUT requests for standard Better Auth routes.
 * @type {import('@sveltejs/kit').RequestHandler}
 */
export const PUT = handler;

/**
 * Handle DELETE requests for standard Better Auth routes.
 * @type {import('@sveltejs/kit').RequestHandler}
 */
export const DELETE = handler;

/**
 * Handle PATCH requests for standard Better Auth routes.
 * @type {import('@sveltejs/kit').RequestHandler}
 */
export const PATCH = handler;

/**
 * Handle OPTIONS requests for standard Better Auth routes.
 * @type {import('@sveltejs/kit').RequestHandler}
 */
export const OPTIONS = handler; 